### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by paulmadore** [valerylisay/digitalocean-api#3]
Just want a little script to map out my domains on DO. Got it worked out and then and this: 

Traceback (most recent call last):
  File "/var/www/html/random/domainmap.py", line 7, in <module>
    domains = client.domains.list_domain_records(all)
  File "build/bdist.linux-i686/egg/digitalocean/api/v2/domains.py", line 32, in list_domain_records
  File "build/bdist.linux-i686/egg/digitalocean/api/baseapi.py", line 92, in request
digitalocean.api.exceptions.ResponseError: Server did not respond. 500 Internal Server Error

Probably something wrong in here: 

`#!/usr/bin/python2
# -*- coding: UTF-8 -*-
import json
from json import decoder
from digitalocean import ClientV2
client = ClientV2(token='<snip>')
domains = client.domains.list_domain_records(all)

with open('/var/www/html/random/digitalocean-map.txt', 'w+') as outMap:
    outMap.write(str(domains))
    outMap.close()`

**Comment by paulmadore** [comment]
Note: I have previously made it dump all the data into a very unusable json format. I'm trying to do a bit more with it. Suggestions appreciated.
